name: star_sticker
description: "A Flutter Sticker SDK"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
    
  http: ^1.4.0
  provider: ^6.1.5
  flutter_dotenv: ^5.0.0
  image_picker: ^0.8.5+3
  image_editor: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
